[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "WebKitGTK"
stereotype = '{"browserName": "WebKitGTK", "browserVersion": "2.34.1", "platformName": "Linux"}'
max-sessions = 1
webdriver-executable = '/usr/bin/WebKitWebDriver'

